# Generated by cpp11: do not edit by hand

dust2_system_seirs_act_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_seirs_act_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_internals`, ptr, include_coefficients, include_history)
}

dust2_system_seirs_act_run_to_time <- function(ptr, r_time) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_run_to_time`, ptr, r_time)
}

dust2_system_seirs_act_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_seirs_act_time <- function(ptr) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_time`, ptr)
}

dust2_system_seirs_act_set_state_initial <- function(ptr) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_set_state_initial`, ptr)
}

dust2_system_seirs_act_set_state <- function(ptr, r_state) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_set_state`, ptr, r_state)
}

dust2_system_seirs_act_reorder <- function(ptr, r_index) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_reorder`, ptr, r_index)
}

dust2_system_seirs_act_rng_state <- function(ptr) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_rng_state`, ptr)
}

dust2_system_seirs_act_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_set_rng_state`, ptr, r_rng_state)
}

dust2_system_seirs_act_set_time <- function(ptr, r_time) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_set_time`, ptr, r_time)
}

dust2_system_seirs_act_update_pars <- function(ptr, pars) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_update_pars`, ptr, pars)
}

dust2_system_seirs_act_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_MixSwitchEpi_dust2_system_seirs_act_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}
