## Generated by dust2 (version 0.3.28) - do not edit
seirs_act <- structure(
  function() get("seirs_act"),
  class = "dust_system_generator",
  name = "seirs_act",
  package = "MixSwitchEpi",
  path = NULL,
  parameters = data.frame(
    name = c("S0", "E0", "m", "swch", "beta", "sigma", "gamma", "omega", "n_activity", "class_sizes", "activity_scores"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(1L, 1L, 2L, 2L, 0L, 0L, 0L, 0L, 0L, 1L, 1L)
  ),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE
  ),
  default_dt = NULL
)
