// Generated by odin2 (version 0.3.39) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(seirs_act)]]
// [[dust2::time_type(continuous)]]
// [[dust2::parameter(S0, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(E0, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(m, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(swch, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(beta, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(sigma, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(gamma, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(omega, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(n_activity, type = "int", rank = 0, required = TRUE, constant = TRUE)]]
// [[dust2::parameter(class_sizes, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(activity_scores, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
class seirs_act {
public:
  seirs_act() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 4> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> S;
      dust2::array::dimensions<2> swch;
      dust2::array::dimensions<1> switch_s;
    } dim;
    real_type beta;
    real_type sigma;
    real_type gamma;
    real_type omega;
    int n_activity;
    std::vector<real_type> S0;
    std::vector<real_type> E0;
    std::vector<real_type> m;
    std::vector<real_type> swch;
    std::vector<real_type> class_sizes;
    std::vector<real_type> activity_scores;
  };
  struct internal_state {
    std::vector<real_type> switch_s_tmp;
    std::vector<real_type> switch_e_tmp;
    std::vector<real_type> switch_i_tmp;
    std::vector<real_type> switch_r_tmp;
    std::vector<real_type> s_ij;
    std::vector<real_type> switch_s;
    std::vector<real_type> switch_e;
    std::vector<real_type> switch_i;
    std::vector<real_type> switch_r;
    std::vector<real_type> lambda;
  };
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type beta = dust2::r::read_real(parameters, "beta");
    const real_type sigma = dust2::r::read_real(parameters, "sigma");
    const real_type gamma = dust2::r::read_real(parameters, "gamma");
    const real_type omega = dust2::r::read_real(parameters, "omega");
    const int n_activity = dust2::r::read_int(parameters, "n_activity");
    dim.S.set({static_cast<size_t>(n_activity)});
    dim.swch.set({static_cast<size_t>(n_activity), static_cast<size_t>(n_activity)});
    dim.switch_s.set({static_cast<size_t>(n_activity)});
    std::vector<real_type> S0(dim.S.size);
    dust2::r::read_real_array(parameters, dim.S, S0.data(), "S0", true);
    std::vector<real_type> E0(dim.S.size);
    dust2::r::read_real_array(parameters, dim.S, E0.data(), "E0", true);
    std::vector<real_type> m(dim.swch.size);
    dust2::r::read_real_array(parameters, dim.swch, m.data(), "m", true);
    std::vector<real_type> swch(dim.swch.size);
    dust2::r::read_real_array(parameters, dim.swch, swch.data(), "swch", true);
    std::vector<real_type> class_sizes(dim.S.size);
    dust2::r::read_real_array(parameters, dim.S, class_sizes.data(), "class_sizes", true);
    std::vector<real_type> activity_scores(dim.S.size);
    dust2::r::read_real_array(parameters, dim.S, activity_scores.data(), "activity_scores", true);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"E", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"I", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"R", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, beta, sigma, gamma, omega, n_activity, S0, E0, m, swch, class_sizes, activity_scores};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> switch_s_tmp(shared.dim.swch.size);
    std::vector<real_type> switch_e_tmp(shared.dim.swch.size);
    std::vector<real_type> switch_i_tmp(shared.dim.swch.size);
    std::vector<real_type> switch_r_tmp(shared.dim.swch.size);
    std::vector<real_type> s_ij(shared.dim.swch.size);
    std::vector<real_type> switch_s(shared.dim.switch_s.size);
    std::vector<real_type> switch_e(shared.dim.switch_s.size);
    std::vector<real_type> switch_i(shared.dim.switch_s.size);
    std::vector<real_type> switch_r(shared.dim.switch_s.size);
    std::vector<real_type> lambda(shared.dim.S.size);
    return internal_state{switch_s_tmp, switch_e_tmp, switch_i_tmp, switch_r_tmp, s_ij, switch_s, switch_e, switch_i, switch_r, lambda};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.beta = dust2::r::read_real(parameters, "beta", shared.beta);
    shared.sigma = dust2::r::read_real(parameters, "sigma", shared.sigma);
    shared.gamma = dust2::r::read_real(parameters, "gamma", shared.gamma);
    shared.omega = dust2::r::read_real(parameters, "omega", shared.omega);
    dust2::r::read_real_array(parameters, shared.dim.S, shared.S0.data(), "S0", false);
    dust2::r::read_real_array(parameters, shared.dim.S, shared.E0.data(), "E0", false);
    dust2::r::read_real_array(parameters, shared.dim.swch, shared.m.data(), "m", false);
    dust2::r::read_real_array(parameters, shared.dim.swch, shared.swch.data(), "swch", false);
    dust2::r::read_real_array(parameters, shared.dim.S, shared.class_sizes.data(), "class_sizes", false);
    dust2::r::read_real_array(parameters, shared.dim.S, shared.activity_scores.data(), "activity_scores", false);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state[i - 1 + 0] = shared.S0[i - 1] * shared.class_sizes[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state[i - 1 + shared.odin.offset.state[1]] = shared.E0[i - 1] * shared.class_sizes[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state[i - 1 + shared.odin.offset.state[2]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state[i - 1 + shared.odin.offset.state[3]] = 0;
    }
  }
  static void rhs(real_type time, const real_type* state, const shared_state& shared, internal_state& internal, real_type* state_deriv) {
    const auto * S = state + 0;
    const auto * E = state + shared.odin.offset.state[1];
    const auto * I = state + shared.odin.offset.state[2];
    const auto * R = state + shared.odin.offset.state[3];
    for (size_t i = 1; i <= shared.dim.swch.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.swch.dim[1]; ++j) {
        internal.switch_s_tmp[i - 1 + (j - 1) * shared.dim.swch.mult[1]] = S[i - 1] * shared.swch[i - 1 + (j - 1) * shared.dim.swch.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.swch.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.swch.dim[1]; ++j) {
        internal.switch_e_tmp[i - 1 + (j - 1) * shared.dim.swch.mult[1]] = E[i - 1] * shared.swch[i - 1 + (j - 1) * shared.dim.swch.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.swch.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.swch.dim[1]; ++j) {
        internal.switch_i_tmp[i - 1 + (j - 1) * shared.dim.swch.mult[1]] = I[i - 1] * shared.swch[i - 1 + (j - 1) * shared.dim.swch.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.swch.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.swch.dim[1]; ++j) {
        internal.switch_r_tmp[i - 1 + (j - 1) * shared.dim.swch.mult[1]] = R[i - 1] * shared.swch[i - 1 + (j - 1) * shared.dim.swch.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.swch.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.swch.dim[1]; ++j) {
        internal.s_ij[i - 1 + (j - 1) * shared.dim.swch.mult[1]] = shared.m[i - 1 + (j - 1) * shared.dim.swch.mult[1]] * I[j - 1] / shared.class_sizes[j - 1];
      }
    }
    for (size_t i = 1; i <= shared.dim.switch_s.size; ++i) {
      internal.switch_s[i - 1] = dust2::array::sum<real_type>(internal.switch_s_tmp.data(), shared.dim.swch, {0, shared.dim.swch.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.switch_s.size; ++i) {
      internal.switch_e[i - 1] = dust2::array::sum<real_type>(internal.switch_e_tmp.data(), shared.dim.swch, {0, shared.dim.swch.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.switch_s.size; ++i) {
      internal.switch_i[i - 1] = dust2::array::sum<real_type>(internal.switch_i_tmp.data(), shared.dim.swch, {0, shared.dim.swch.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.switch_s.size; ++i) {
      internal.switch_r[i - 1] = dust2::array::sum<real_type>(internal.switch_r_tmp.data(), shared.dim.swch, {0, shared.dim.swch.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      internal.lambda[i - 1] = shared.beta * shared.activity_scores[i - 1] * dust2::array::sum<real_type>(internal.s_ij.data(), shared.dim.swch, {i - 1, i - 1}, {0, shared.dim.swch.dim[1] - 1});
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state_deriv[i - 1 + 0] = -internal.lambda[i - 1] * S[i - 1] + shared.omega * R[i - 1] + internal.switch_s[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state_deriv[i - 1 + shared.odin.offset.state[1]] = internal.lambda[i - 1] * S[i - 1] - shared.sigma * E[i - 1] + internal.switch_e[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state_deriv[i - 1 + shared.odin.offset.state[2]] = shared.sigma * E[i - 1] - shared.gamma * I[i - 1] + internal.switch_i[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state_deriv[i - 1 + shared.odin.offset.state[3]] = shared.gamma * I[i - 1] - shared.omega * R[i - 1] + internal.switch_r[i - 1];
    }
  }
};
