

using TidierData 

"""
Make a parameterisation. Useful for tests etc.
Scalar parameters are taken from (Britton et al., 2020) Science
and SARS-CoV-2-like.

This also generates the initial state using the supplied initial_rule (e.g., 'uniform')
and the infected_class if specified. 


    Returns a tuple of of the struct
"""
function make_parset(ξ::Float64, n_activity::Int, pop_size::Int, switch_model, 
                     mix_model, ε::Float64, mean_activity::Float64, variance_activity::Float64)
    scalars = get_scalar_parms()
    β = scalars.β
    σ = scalars.σ
    γ = scalars.γ 
    ω = scalars.ω
 
    # activity class scoring and sizes etc. 
    act_levels = gamma_bin_expectations(mean = mean_activity, 
                                        variance = variance_activity, 
                                        n_activity = n_activity)
    class_sizes = fill(Int(pop_size / n_activity),n_activity)  # equal sized activity classes
    

    if switch_model == "uniform"
        W = simple_switching(ξ, n_activity)
    elseif switch_model == "adjacent"
        W = constrained_switching(ξ, n_activity)
    else
        println("unrecognised switching model specified. use either `uniform` or `adjacent`")
    end

    if mix_model == "garnett"
        M = make_garnett_contact(ε, n_activity, act_levels, class_sizes)
    else
        println("unrecongised mixing model specified. use `garnett`.")
    end
    parset = SEIRSStochParams(β, σ, γ, ω, #constructing the relevant struct
                        M, W, n_activity, 
                        class_sizes, act_levels, 
                        pop_size)

    return parset # returns a tuple of simulation parameters + initial conditions
end


"""
    find_steadystate(W::Matrix{Float64})

Find steady-state generated by CTMC generator matrix

This is used in testing for the equal-sized activity class
criterion in the testset.

"""
function find_steadystate(W::Matrix{Float64})
    n = size(W, 1)
    A = vcat(W', ones(1, n))
    b = vcat(zeros(n), [1.0])
    π = A \ b
    return π[1:n]
end



"""
    validate_generator(W)

Validate the generator matrix Q which defines the flow between activity classes

"""
function validate_generator(W)
    n = size(W, 1)
    for i = 1:n
        if abs(sum(W[i, :])) > 1e-10
            error("Generator matrix rows must sum to zero. Row $i sums to $(sum(W[i, :]))")
        end
    end
    for i = 1:n, j = 1:n
        if i != j && W[i, j] < 0
            error("Off-diagonal elements must be non-negative. W[$i,$j] = $(W[i,j])")
        end
    end
    return true
end

"""
    validate_class_sizes(class_sizes::Vector::Int, total_pop::Int)

Verify that the `class_sizes` sum to the `tot_pop`
"""
function validate_class_sizes(class_sizes::Vector{Int}, total_pop::Int)
    if sum(class_sizes) != total_pop
        error("Sum of class sizes must equal total population size.")
    end
end



"""
    spectral_radius(M)

Return the spectral radius (largest real part of eigenvalues) of matrix `M`.
Helper function.
"""
function spectral_radius(M::AbstractMatrix{<:Number})
    vals = eigvals(Matrix(M))
    return maximum(real(vals))
end


"""
    default_parametrisation(; kwargs...)

Return a simple default SEIRSStochParams and initial state. This helper is small and
used in tests. Keyword args override defaults.

# Arguments

β::Float64: 
σ::Float64: 



# Note 

This produces an uncalibrated parameter set. If there is a desired R0, this needs to be calibrated against separately


"""
function default_parametrisation(; β=0.0934, σ=1/3, γ=1/4, ω=0.0,
                                n_activity::Int=5, Ntot::Int=5000,
                                ξ::Float64=0.1, ε::Float64=0.2,
                                act_levels::Union{Nothing,Vector{Float64}}=nothing,
                                gamma_mean::Float64=5.0,
                                gamma_variance::Float64=5.0,
                                p_inf::Int=1,
                                init_mode::Symbol = :uniform,
                                init_class::Int=1,
                                tspan::Tuple{Float64,Float64} = (0.0, 305.0))

    if act_levels === nothing
        act_levels = gamma_bin_expectations(mean = gamma_mean, #using the Discretised Gamma dist to derive the activity scores
                                            variance = gamma_variance,
                                            n_activity = n_activity)
    end

    class_sizes = fill(Int(Ntot / n_activity), n_activity)
    pop_size = sum(class_sizes)

    # contact and switching
    M = make_garnett_contact(ε, n_activity, act_levels, class_sizes)
    W = uniform_switching(ξ, n_activity)

    params = SEIRSStochParams(β, σ, γ, ω, M, W, n_activity, class_sizes, act_levels, pop_size)

    # build initial state using absolute number infected (p_inf)
    initial_state = make_initial_state(class_sizes, p_inf; init_mode = init_mode, init_class = init_class)

    return params, initial_state, tspan
end

